/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// biome-ignore lint: disable
// This file is auto-generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Account: typeof import('./components/Account.vue')['default']
    BuyCoffee: typeof import('./components/BuyCoffee.vue')['default']
    CoffeeCard: typeof import('./components/CoffeeCard.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Hero: typeof import('./components/Hero.vue')['default']
    HowItWork: typeof import('./components/HowItWork.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    Profile: typeof import('./components/Profile.vue')['default']
    Recent: typeof import('./components/Recent.vue')['default']
    RecentCard: typeof import('./components/RecentCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Wallet: typeof import('./components/Wallet.vue')['default']
  }
}
